name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  associated-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Associated PRs
        run: |
          set -e
          PRS=$(curl --silent --show-error \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/pulls)
          PRS_COUNT=$(echo "$PRS" | jq -r 'length')
          echo "$PRS_COUNT"
          if [ "$PRS_COUNT" != "0" ]; then
            echo "$PRS" | jq -r '.[] | .html_url'
          else
            echo "No PR associated with this commit"
          fi

  build-artifact:
    runs-on: ubuntu-latest
    needs: [associated-prs]
    steps:
      - name: Build
        run: echo "Artifact build"
  
  deploy-staging:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs: [build-artifact]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
  
  deploy-production:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: [build-artifact, deploy-staging]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
