name: CD

on:
  pull_request_target:
    branches: 
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  build-artifact:
    if: ${{ github.event.pull_request.merged }} # TODO: this breaks the workflow_dispatch event
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Artifact build"
  
  deploy-staging:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs: [build-artifact]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
  
  deploy-production:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: [build-artifact, deploy-staging]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
