name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2.4.0
      - run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/pulls | jq

  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Artifact build"
  
  deploy-staging:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs: [build-artifact]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
  
  deploy-production:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: [build-artifact, deploy-staging]
    steps:
      - name: Deploy to staging
        run: echo "Deployed to staging"
