# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  # This workflow has one sample job that simply prints a message, and always succeed.
  # In reality this would contain all the CI jobs (build, lint, test, ...)
  pass-all:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
